# Generated by Django 3.0 on 2019-12-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Диагноз')),
                ('info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание диагноза')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'М'), ('f', 'Ж')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название препарата')),
                ('contraindication', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Противопоказания')),
                ('indication', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Показания')),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=30, verbose_name='Фамилия')),
                ('middlename', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Отчеcтво')),
                ('birthday', models.DateField()),
                ('amb_card', models.IntegerField(unique=True, verbose_name='Номер абулаторной карты')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.Gender', verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=30, verbose_name='Фамилия')),
                ('middlename', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Отчеcтво')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.Gender', verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Специальность служащего', max_length=60, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название процедуры')),
                ('info', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание процедуры')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(help_text='Медицинское учреждение, в котором находится отделение', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='Мед. учреждение'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Наименование отделения', max_length=60, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Наименование медицинского учереждения', max_length=60, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание рецепта')),
                ('time_recieption', models.DateTimeField(auto_now_add=True)),
                ('diagnose', models.ForeignKey(help_text='Диагноз, по которому выписан рецепт', on_delete=django.db.models.deletion.PROTECT, to='hospital.Diagnose', verbose_name='Диагноз')),
                ('doctor', models.ForeignKey(help_text='Врач, который выписал рецепт', on_delete=django.db.models.deletion.PROTECT, to='hospital.Person', verbose_name='Врач')),
                ('medicines', models.ManyToManyField(help_text='Список препаратов по рецепту', to='hospital.Medicine', verbose_name='Препараты')),
                ('pacient', models.ForeignKey(help_text='Пациент, которому выписан рецепт', on_delete=django.db.models.deletion.CASCADE, to='hospital.Pacient', verbose_name='Пациент')),
                ('prucedures', models.ManyToManyField(help_text='Список процедур, показанных по рецепту', to='hospital.Procedure', verbose_name='Процедуры')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Специальность, по которой работает представитель персонала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Post', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Номер кабинета')),
                ('name', models.CharField(blank=True, help_text='Наименование кабинета', max_length=60, null=True, verbose_name='Наименование')),
                ('department', models.ForeignKey(blank=True, help_text='Медицинское отделение, в котором находится кабинет', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Department', verbose_name='Отделение')),
            ],
        ),
    ]
