# Generated by Django 3.0 on 2019-12-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20191227_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cabinet',
            field=models.ManyToManyField(help_text='Список кабинетов, в которых может принимать работник', to='hospital.Cabinet', verbose_name='Кабинеты'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Медицинское отделение, в котором числится работник', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Department', verbose_name='Отделение'),
        ),
    ]
