# Generated by Django 3.0 on 2019-12-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20191227_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='time_recieption',
            field=models.DateTimeField(verbose_name='Дата приема'),
        ),
    ]
