# Generated by Django 3.0 on 2019-12-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20191227_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='medicines',
            field=models.ManyToManyField(blank=True, help_text='Список препаратов по рецепту', null=True, to='hospital.Medicine', verbose_name='Препараты'),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='prucedures',
            field=models.ManyToManyField(blank=True, help_text='Список процедур, показанных по рецепту', null=True, to='hospital.Procedure', verbose_name='Процедуры'),
        ),
    ]
