# Generated by Django 3.0 on 2019-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20191227_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cabinet',
            new_name='cabinets',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.AddField(
            model_name='person',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Медицинские отделения, в которых числится работник', null=True, to='hospital.Department', verbose_name='Отделения'),
        ),
    ]
